name: lector_sync_flutter
description: Sistema de Sincronizaci贸n de Lectura P2P con Flutter
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  # Base de datos local
  isar: ^3.1.0+1
  isar_flutter_libs: ^3.1.0+1
  path_provider: ^2.1.1

  # Gesti贸n de estado
  flutter_bloc: ^8.1.3
  equatable: ^2.0.5

  # Utilidades
  uuid: ^4.2.1
  crypto: ^3.0.3
  intl: ^0.18.1

  # Lectores PDF/EPUB
  syncfusion_flutter_pdfviewer: ^24.1.41
  epub_view: ^3.1.0

  # P2P (implementaci贸n futura)
  # flutter_webrtc: ^0.9.47
  # multicast_dns: ^0.3.2

  # UI
  cupertino_icons: ^1.0.6
  google_fonts: ^6.1.0
  flutter_slidable: ^3.0.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0
  
  # Generador de c贸digo Isar
  isar_generator: ^3.1.0+1
  build_runner: ^2.4.7

flutter:
  uses-material-design: true

  # assets:
  #   - assets/images/
  #   - assets/fonts/
